name: Deploy Photo judge with Docker

on:
  push:
    branches: [main-deploy]

  pull_request:
    branches: [main-deploy]

jobs:
  deploy:
    runs-on: self-hosted  # 使用你配置的自托管运行器

    steps:
      # 第一步：获取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：构建项目（你服务器已经安装了 JDK 17）
      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests

      # 第三步：构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t photo-app:latest .

      # 第四步：停止并移除旧容器（如果存在）
      - name: Stop and remove old container
        run: |
          docker stop photo-app || true
          docker rm photo-app || true

      # 第五步：启动容器
      - name: Run Docker container
        run: |
          docker run -d \
            --name photo-app \
            -p 8080:8080 \
            photo-app:latest

      # 第六步：清理旧的悬挂镜像
      # 这个步骤会删除所有没有被任何标签引用的镜像，防止磁盘空间被占用。
      - name: Clean up old dangling Docker images
        run: |
          docker image prune -f